name: CI
# Trigger the workflow on push or pull request,
# but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checks-out repository and run our tests action
    - uses: actions/checkout@v2
    - uses: ./tests
